### ISSUE TITLE
Error - npm run build

### ISSUE THREAD

**Issue by noobchamp** [lixmal/keepass4web#2]
```
root@ubuntu:/opt/keepass4web# npm run build

> KeePass4Web@0.6.1 build /opt/keepass4web
> NODE_ENV=production ./node_modules/.bin/browserify -t browserify-css -p [ minifyify --no-map ] -t [ babelify --presets [ es2015 react ] ] src/scripts/app.js -o public/scripts/bundle.js; sed -i 's/node_modules\/bootstrap\/dist\///g' public/scripts/bundle.js

Error: Cannot find module 'history' from '/opt/keepass4web/src/scripts'
    at /opt/keepass4web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/opt/keepass4web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/opt/keepass4web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/opt/keepass4web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/opt/keepass4web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /opt/keepass4web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```
Can you help me?

**Comment by lixmal** [comment]
Seems like history wasn't installed properly.
Can you run a `npm install history` beforehand?

**Comment by noobchamp** [comment]
sorry, you can close this thread. 
It was a mistake on my part.

Thanks.
